/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_chu_jnitest_HelloNDK */

#ifndef _Included_com_example_chu_jnitest_HelloNDK
#define _Included_com_example_chu_jnitest_HelloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_chu_jnitest_HelloNDK
 * Method:    getHelloNDKString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_chu_jnitest_HelloNDK_getHelloNDKString
  (JNIEnv *, jobject);

/*
 * Class:     com_example_chu_jnitest_HelloNDK
 * Method:    setDeviceDriver
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_chu_jnitest_HelloNDK_setDeviceDriver
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
